/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.gui;

import java.awt.Event;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.net.MalformedURLException;
import java.rmi.RemoteException;
import java.util.List;

import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;

import br.ufrn.Controle.MedicoFachada;
import br.ufrn.Controle.MedicoFachadaInterface;
import br.ufrn.entidades.Alerta;
import br.ufrn.entidades.SinalVital;
import br.ufrn.excecoes.BDexception;

/**
 *
 * @author jorge
 */
public class Historico extends javax.swing.JFrame {

	/**
	 * Creates new form Historico
	 */
	private MedicoFachadaInterface fachada;

	public Historico(String paciente) {
		initComponents();

		jTpacienteNome.setText(paciente);
		jTpacienteNome.setEnabled(false);

		try {
			fachada = new MedicoFachada(null);
		} catch (RemoteException | MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void listarHistorico() throws BDexception {

		if (jDateChooser1.getDate() == null) {
			return;
		}
		List<Alerta> alertas = fachada.recuperarAlertas(jTpacienteNome.getText(), jDateChooser1.getDate());

		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

		while (model.getRowCount() > 0) {
			model.removeRow(0);
		}

		for (int i = 0; i < alertas.size(); i++) {

			model.addRow(new String[] { null, null, null, null });
			Alerta a = alertas.get(i);

			Integer pressao = a.getSinaisVitais().get(SinalVital.PRESSAO.toString());
			Integer batimentos = a.getSinaisVitais().get(SinalVital.BATIMENTOS.toString());
			Integer glicose = a.getSinaisVitais().get(SinalVital.GLICOSE.toString());

			if (pressao > 7 && pressao < 14) {
				preencherCelula(model, pressao.toString(), i, 0);
			} else {
				preencherCelulaVermelho(model, pressao.toString(), i, 0);
			}
			if (batimentos > 49 && batimentos < 131) {
				preencherCelula(model, batimentos.toString(), i, 1);
			} else {
				preencherCelulaVermelho(model, batimentos.toString(), i, 1);
			}
			if (glicose > 59 && glicose < 129) {
				preencherCelula(model, glicose.toString(), i, 2);
			} else {
				preencherCelulaVermelho(model, glicose.toString(), i, 2);
			}

			preencherCelula(model,
					a.getData().getHours() + ":" + a.getData().getMinutes() + ":" + a.getData().getSeconds(), i, 3);

		}
	}

	private void preencherCelula(DefaultTableModel model, String valor, int linha, int coluna) {
		model.setValueAt(valor, linha, coluna);
	}

	private void preencherCelulaVermelho(DefaultTableModel model, String valor, int linha, int coluna) {
		model.setValueAt("<html><font color = red>" + valor + "</html><red>", linha, coluna);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jTpacienteNome = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jDateChooser1 = new com.toedter.calendar.JDateChooser();

		jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
			public void propertyChange(java.beans.PropertyChangeEvent evt) {
				try {
					listarHistorico();
				} catch (BDexception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {},
				new String[] { "Pressão", "Batimentos", "Glicose", "Hora" }));
		jScrollPane1.setViewportView(jTable1);

		jLabel1.setText("Paciente:");

		jTpacienteNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Data:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628,
														Short.MAX_VALUE)
												.addContainerGap())
										.addGroup(
												jPanel1Layout.createSequentialGroup().addComponent(jLabel1)
														.addGap(2, 2, 2).addComponent(jTpacienteNome)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel2).addGap(4, 4, 4)
								.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
										javax.swing.GroupLayout.PREFERRED_SIZE).addGap(21, 21, 21)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel1)
										.addComponent(jTpacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2))
								.addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Historico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Historico(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private com.toedter.calendar.JDateChooser jDateChooser1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTpacienteNome;
	// End of variables declaration//GEN-END:variables
}
